# THIS IS A LOCAL 'docker-compose' FILE FOR LOCAL BUILDS AND TESTS
version: '3'
services:
  postgres:
    build: ./Database
    container_name: DB-postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: DB-postgres-interface
    restart: always
    ports:
      - 8082:8080

  api:
    build: ./Minitwit-api
    container_name: API
    depends_on:
      - postgres
    ports:
      - 8080:8080

  app:
    build: ./ITU_MiniTwit
    container_name: APP
    command: >
      sh -c "
            python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: DB-postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: szymongalecki/grafana
    container_name: grafana
    ports:
      - "5003:3000"

volumes:
  postgres_volume:
