version: '3'
services:
  mongo:
    image: mongo
    container_name: DB
    restart: always
    volumes:
      - database_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    container_name: DB-viewer
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/

  api:
    build: ./Minitwit-api
    container_name: API
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  app:
    build: ./ITU_MiniTwit
    container_name: APP
    depends_on:
      - mongo
    ports:
      - "8000:8000"

volumes:
  database_volume:
