# Passwords are explicit, for tests only, do not use for production :)
version: '3'
services:
  postgres:
    build: ./Database
    container_name: DB-postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: DB-postgres-interface
    restart: always
    ports:
      - 8082:8080

  api:
    build: ./Minitwit-api
    container_name: API
    depends_on:
      - postgres
    ports:
      - 8080:8080
  app:
    build: ./ITU_MiniTwit
    container_name: APP
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - postgres

volumes:
  postgres_volume:
