# Passwords are explicit, for tests only, do not use for production :)
version: '3'
services:
  postgres:
    # image: ${DOCKER_USERNAME}/minitwitdb
    build: ./Database
    container_name: DB-postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: DB-postgres-interface
    restart: always
    ports:
      - 8082:8080

  api:
    # image: ${DOCKER_USERNAME}/apiminitwit
    build: ./Minitwit-api
    container_name: API
    depends_on:
      - postgres
    ports:
      - 8080:8080
  app:
    # image: ${DOCKER_USERNAME}/minitwitimage
    build: ./ITU_MiniTwit
    container_name: APP
    command: >
      sh -c "
            python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: DB-postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    #image: grafana/grafana:latest
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/exported_dashboard.json"

volumes:
  postgres_volume:
