# Passwords are explicit, for tests only, do not use for production :)
version: '3'
services:
  mongo:
    image: mongo
    container_name: DB-mongo
    restart: always
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: DB-mongo-interface
    depends_on:
      - mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
    ports:
      - 8081:8081

  postgres:
    image: postgres
    container_name: DB-postgres
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: DB-postgres-interface
    restart: always
    ports:
      - 8082:8080

  api:
    build: ./Minitwit-api
    container_name: API
    depends_on:
      - mongo
      - postgres
    ports:
      - 8080:8080

  app:
    build: ./ITU_MiniTwit
    container_name: APP
    depends_on:
      - mongo
      - postgres
    ports:
      - 8000:8000

volumes:
  mongo_volume:
  postgres_volume:
