global:
  scrape_interval:     15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name:       'itu-minittwit-app'
    static_configs:
      - targets: ['API:8080']
        labels:
          group: 'production'
