---
name: Static check

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flake8
          pip install bandit
          pip install black
          pip install -r ./ITU_MiniTwit/requirements.txt
          pip install -r ./Minitwit-api/requirements.txt

      - name: Run Flake8
        run: |
          flake8
        continue-on-error: true

      - name: Run Bandit
        run: |
          bandit -r . --configfile bandit.yml --severity=HIGH
        continue-on-error: true

      - name: Run Black
        run: |
          black .
        continue-on-error: false